### ISSUE TITLE
variable length array of non-pod element type in glv_draw.h

### ISSUE THREAD

**Issue by Geistyp** [AlloSphere-Research-Group/GLV#7]
OSX 10.10, xcode 6.3.2
```c++
template<int N, int A>
void spokes(float l, float t, float r, float b){
	int N2 = N<<1;
	Point2 pts[N2];  // this will cause compile error
	float cx = (l+r)/2;
	float cy = (t+b)/2;
	genEllipse(pts+1,N,2, A/360.,1, l,t,r,b);
	for(int i=0; i<N2; i+=2) pts[i](cx,cy);
	paint(Lines, pts, GLV_ARRAY_SIZE(pts));
}
```

```c++
const int N2 = N << 1; 
```
I change to this then I can compile it

**Comment by LancePutnam** [comment]
In the current master branch, it is indeed const int. Is this from an older version (in glv_conf.h)?

**Comment by Geistyp** [comment]
Yes, it's older version, not check, sorry. I use old achive from website. 

tks for quick reply, i will replace to lastest github version.

by the way, is glv works fine in opengles1/2/3?
