### ISSUE TITLE
"Stack around the variable 'v' was corrupted. " in fromToken<bool>()

### ISSUE THREAD

**Issue by Geistyp** [AlloSphere-Research-Group/GLV#8]
Latest github version, vs2013, win7 x64

Copy fromToken for simple test:
```C++
const char* s = "{0, 0, 1, 0}";
const char * match = "01";
const char * format = "%hhi";	// "%c"
int stride = 1;

bool* dst = new bool[4];

int i = -1;
bool v;
while (++i < 4 && s){
	if (!(s = strpbrk(s, match))) break;
	bool v; sscanf(s, format, &v);
	dst[i*stride] = v;
	s = strpbrk(s, " ,");
}
```
"%c" works, maybe in my compiler bool is shorter then "%hhi"(unsigned char)?

**Comment by LancePutnam** [comment]
Perhaps. In general, the problem is likely an incorrect assumption that a bool and signed char occupy the same amount of memory. If I replace 'bool v' with 'char v' in the while loop leaving the format "%hhi", then it works. Can you try the same? If it works, then I will specialize fromToken in this way for bool.

**Comment by Geistyp** [comment]
```c++
int i = -1;
while (++i < 4 && s){
	if (!(s = strpbrk(s, match))) break;
	char v; sscanf(s, format, &v);  // replace bool v
	dst[i*stride] = v;
	s = strpbrk(s, " ,");
}
```
like this? not work, still corrupted

Following works:
1. "%hhi" / "%hhc" --- int v / unsigned in v
2. "%hhc" --- char v / unsigned char v

**Comment by LancePutnam** [comment]
"%c" is not correct since we want a number not a character. Even though "%hhi" works, I would prefer avoiding it since it is C99. Can you try "%i" and int v?

**Comment by Geistyp** [comment]
"%i" and int v works. 
int v is long enough for "%i" and "%hhi".
